# This is a basic workflow to help you get started with Actions

name: First Workflow

on: [issues, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Expression
        run: echo "${{ toJSON(github.event) }}"
      - name: Print goodbye
        run: echo "Bye"


